### ISSUE TITLE
[Question] Update / Port

### ISSUE THREAD

**Issue by accessdenied0** [Christofmeg/JEI-Recipe-History#3]
Heyo @Christofmeg ! 

I am sorry to be _that guy_ but I really loved the mod for the 1.12.2 in its original and I was a bit excited to see your port for newer versions. 
Esp. since I play alot in like with GT in the newer versions (mostly forge 1.20.1) I miss that plugin. 
I was hoping that you might plan to update to this version or if possible even to port it to REI? (I am not sure if the REI - JEI Plugin mod would work)...

Like I said I hate to like be that person who asked for an update, but I really would love to see it updated!

**Comment by Christofmeg** [comment]
@accessdenied0 now I will continue to work where I left off

**Comment by Christofmeg** [comment]
I'm sorry, but at this point in time there won't be any updates anytime soon
