### ISSUE TITLE
Also hate to be that guy.. But.. If you could update this to 1.20.1 that would be very sick!

### ISSUE THREAD

**Issue by EAGBCD** [Christofmeg/JEI-Recipe-History#4]
https://www.curseforge.com/minecraft/mc-mods/jei-recipe-history

Such a great mod! And very hard to live without. 

If its a lot of work / you don't want to all good. If its easy or you want to I would be really happy. 

EMI has this on modern versions but EMI is bulkyish, and hard to add to modpacks. This is the one feature I want in a standalone mod. 

Thanks, and sorry, and if you do this thats awesome, and if you dont I understand.

**Comment by Christofmeg** [comment]
You're right EMI added this in version [0.7.0](https://modrinth.com/mod/emi/version/0.7.0+1.18.2) and has this implemented across the board as "lookup history" which can be enabled in the config to show on the sidebar

**Comment by EAGBCD** [comment]
Hey sorry, I actually created this after trying EMI and finding it suboptimal for my needs.

EMI has lots of powerful and useful features but I actually prefer simple JEI

EMI is sort of performance heavy 

EMI doesn’t work great for adding to an existing modpack that has customized JEI (hiding recipes for example)

My situation is playing ATM 9, (1.20.1) really needing the recipe history feature because it is so useful, but finding that I don't want any of EMI's features and that its causing problems. 

Your mod, a standalone JEI Recipe History mod is exactly what I was looking for.

Hope this makes sense and thanks for your reply.

**Comment by Christofmeg** [comment]
I'm sorry, but at this point in time there won't be any updates anytime soon
